import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchCount } from './counter/counterAPI';

const initialState = {
  user: null,
  status: 'idle',
};
 
export const userSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers:  (state, action) => {
      login: {
        state.user = action.payload;
      }
      logout: {
        state.user = null;
      }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
 
});

export const { login, logout } = userSlice.actions;

export const selectCount = (state) => state.counter.value;

export default userSlice.reducer;


